### PR TITLE
Resolve issues with API changes from Wyze (2024-02-01)

### LINKED ISSUE #2: Getting an authentication error via Wyze Homebridge plug-in
Hi,

I received an e-mail from Wyze that they had reset my password after detecting suspicious access (homebridge?) - I am not sure. But I played along and changed my password, etc.  Since then, it has broken the Wyze HomeBridge plug-in and keeps failing with a Cloudfront "Blocked Access" error.

I looked at the plug-in source and saw that it was using this wyze-api as it's connector to Wyze.  I figured the auth error was lower down than the HomeBridge Wyze plugin - so I cloned this repo and ran the "example".  

It failed with the same error:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n' +
      '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n' +
      '<TITLE>ERROR: The request could not be satisfied</TITLE>\n' +
      '</HEAD><BODY>\n' +
      '<H1>403 ERROR</H1>\n' +
      '<H2>The request could not be satisfied.</H2>\n' +
      '<HR noshade size="1px">\n' +
      'Request blocked.\n' +
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n" +
      '<BR clear="all">\n' +
      'If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n' +
      '<BR clear="all">\n' +
      '<HR noshade size="1px">\n' +
      '<PRE>\n' +
      'Generated by cloudfront (CloudFront)\n' +
      'Request ID: K12IGdVcVbcgkfCluSWeGKjZPK2hQT1U84W3rS9JmNJwdkb693Pf7Q==\n' +
      '</PRE>\n' +
      '<ADDRESS>\n' +
      '</ADDRESS>\n' +
      '</BODY></HTML>
```

This is vague, but I tried making some direct HTTPS requests to the endpoint (wyze auth api) and got some BAD REQUEST 400's - so something made me think maybe the userAgent was bad.  It didn't seem like Wyze was blocking our requests entirely - just that it didn't like them for some reason.

I noticed the userAgent was hard-coded into the plug-in, and then saw that options.userAgent would allow me to override it.  I'm not sure why I went here, but anyway - I specified my current Firefox userAgent and it worked!

I don't know if Wyze + Cloudfront have started blocking the old userAgent as being invalid/too old  --- or knowing it is coming from this plugin in some way?  (I searched issues on the wyze plugin and Reddit for "fresh" info but nobody else appears to be reporting this...)

The constant I currently see is:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15`

which is OSX 10.15 (same as mine! - but it's old) - and Safari 14 - but 17 is out.

I'm reporting this here because I'm not entirely certain how to fast-track a custom `wyze-api` module into my Homebridge configuration and escalating here so that it can hopefully get incorporated/fixed here and bumped up into an update on the Homebridge plug-in side.

Here is the `index.js` changes I have in the `example` that did work:

```javascript
//const WyzeAPI = require('../src/index') // Local Debug
const WyzeAPI = require("wyze-api");
const Logger = require("@ptkdev/logger");

const logger = new Logger();

const options = {
  username: "***
  password: "***",
  keyId: "****",
  apiKey: "****,
  persistPath: "./scratch",
  logLevel: "debug",
  apiLogEnabled: true,
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0",
};
const wyze = new WyzeAPI(options, logger);

(async () => {
  const devices = await wyze.getDeviceList();
  logger.debug(JSON.stringify(devices));
})();

```

Without fully understanding this codebase - I'm not saying the userAgent is the only fix needed here.  I am not sure why Wyze/Cloudfront would be blocking the UserAgent defined in the constants.

FWIW, I tested the example with the following user agents from my other browsers:

WORKS - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6.1 Safari/605.1.1`

WORKS - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`

WORKS `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

Thanks for all your work on this lib and the HomeBridge plug-in.  Much appreciated!

I hope this info helps.

### PR DESCRIPTION
**Pull request by hgoscenski**
Attempt to resolve https://github.com/jfarmer08/wyze-api/issues/2

- Update check in `_performRequest` to handle `SUCCESS` as valid `msg`, this appears to be a change in the API.
- Update user-agent to be more general, rather than a specific user agent from a browser.

Verification of user agent functionality:

```
[08:21:03] ~/wyze-homebridge λ curl --write-out '%{http_code}' -SsL --output /dev/null -XPOST -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" --header "Content-Type: application/json" --header "apikey: $API_KEY" --header "keyid: $KEY_ID" --header "User-Agent: unofficial-wyze-api/1.0" https://auth-prod.api.wyze.com/api/user/login
200%
```

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -128,7 +128,7 @@ module.exports = class WyzeAPI {
       throw e
     }
     if (result.data.msg) {
-      if (result.data.msg == "DeviceIsOffline") { return result } else
+      if (result.data.msg == "DeviceIsOffline" || result.data.msg != "SUCCESS") { return result } else
```
Comment (tj-noor) [inline src/index.js]:
```suggestion
      if (result.data.msg == "DeviceIsOffline" || result.data.msg == "SUCCESS") { return result } else
```

thanks for the PR - small typo to fix before merging
